
services:

  postgres:
    image: postgres:latest
    container_name: fullstack
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Admin@123$
      - POSTGRES_DB=full_stack
    logging:
      options:
        max-size: 10m
        max-file: "3"

    ports:
      - '5432:5432'
    expose:
      - '5433'

    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - ./uratestdb-data:/var/lib/postgresql/data

